version: "3"
services:

  zeppelin:
    container_name: zeppelin
    image: apache/zeppelin:0.10.1
    ports:
      - 8080:8080
      - 4040:4040
    environment:
      - SPARK_MASTER=${SPARK_MASTER_URL}
      - SPARK_HOME=/opt/spark
      - DOCKER_TIME_ZONE=Europe/Minsk
      - ZEPPELIN_NOTEBOOK_DIR=/notebook
    volumes:
      - ${NOTEBOOK_PATH}:/notebook
      - ${SPARK_HOME}:/opt/spark

  spark-master:
    user: root
    container_name: spark-master
    image: bitnami/spark:3.1.3
    ports:
      - 7080:8080
    command: start-master.sh
    volumes:
      - ${NOTEBOOK_PATH}:/notebook

  spark-worker-a:
    user: root
    container_name: spark-worker-a
    image: bitnami/spark:3.1.3
    ports:
      - 7081:8081
    depends_on:
      - spark-master
    command: start-worker.sh ${SPARK_MASTER_URL} -c 2 -m 2G
    volumes:
      - ${NOTEBOOK_PATH}:/notebook

  spark-worker-b:
    user: root
    container_name: spark-worker-b
    image: bitnami/spark:3.1.3
    ports:
      - 7082:8081
    depends_on:
      - spark-master
    command: start-worker.sh ${SPARK_MASTER_URL} -c 2 -m 2G
    volumes:
      - ${NOTEBOOK_PATH}:/notebook
